spring:
  application:
    name: forknow
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forknow?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    # Pour afficher les requêtes SQL
    spring.jpa.show-sql: true
    # Pour afficher les paramètres dans les requêtes
    spring.jpa.properties.hibernate.format_sql: true
    spring.jpa.properties.hibernate.use_sql_comments: true
    logging.level.org.hibernate.SQL: DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: password



