on:
  push:
 
jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'
      
  test:
    name: Spring test
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew test
      
  build:
   name: Spring build
   runs-on: ubuntu-latest
   needs:
   - get-version
   steps:
     - name: Print version
       run: 
         echo "${{ needs.get-version.outputs.version }}"
        
     - name: Setup java
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
     - name: Setup gradle
       uses: gradle/actions/setup-gradle@v4
     - name: Checkout clone source code
       uses: actions/checkout@v4
     - name: Build with Gradle
       env:
         VERSION: "${{ needs.get-version.outputs.version }}"
         
       run: chmod +x gradlew && ./gradlew bootjar
     - uses: actions/upload-artifact@v4
       with:
           path: build/libs/
